// Generated by: gen
// TypeWriter: gen
// Directive: +gen on *main.AnotherType

// See http://clipperhouse.github.io/gen for documentation

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

package main

import (
	"errors"
)

// AnotherTypes is a slice of type *AnotherType. Use it where you would use []*AnotherType.
// PLURAL START OMIT
type AnotherTypes []*AnotherType

// PLURAL END OMIT

// All verifies that all elements of AnotherTypes return true for the passed func. See: http://clipperhouse.github.io/gen/#All
// ALL START OMIT
func (rcv AnotherTypes) All(fn func(*AnotherType) bool) bool {
	// ALL END OMIT
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of AnotherTypes return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv AnotherTypes) Any(fn func(*AnotherType) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// Count gives the number elements of AnotherTypes that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv AnotherTypes) Count(fn func(*AnotherType) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}

// Distinct returns a new AnotherTypes slice whose elements are unique. See: http://clipperhouse.github.io/gen/#Distinct
func (rcv AnotherTypes) Distinct() (result AnotherTypes) {
	appended := make(map[*AnotherType]bool)
	for _, v := range rcv {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

// DistinctBy returns a new AnotherTypes slice whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv AnotherTypes) DistinctBy(equal func(*AnotherType, *AnotherType) bool) (result AnotherTypes) {
	for _, v := range rcv {
		eq := func(_app *AnotherType) bool {
			return equal(v, _app)
		}
		if !result.Any(eq) {
			result = append(result, v)
		}
	}
	return result
}

// Each iterates over AnotherTypes and executes the passed func against each element. See: http://clipperhouse.github.io/gen/#Each
func (rcv AnotherTypes) Each(fn func(*AnotherType)) {
	for _, v := range rcv {
		fn(v)
	}
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv AnotherTypes) First(fn func(*AnotherType) bool) (result *AnotherType, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no AnotherTypes elements return true for passed func")
	return
}

// IsSortedBy reports whether an instance of AnotherTypes is sorted, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv AnotherTypes) IsSortedBy(less func(*AnotherType, *AnotherType) bool) bool {
	n := len(rcv)
	for i := n - 1; i > 0; i-- {
		if less(rcv[i], rcv[i-1]) {
			return false
		}
	}
	return true
}

// IsSortedDesc reports whether an instance of AnotherTypes is sorted in descending order, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv AnotherTypes) IsSortedByDesc(less func(*AnotherType, *AnotherType) bool) bool {
	greater := func(a, b *AnotherType) bool {
		return less(b, a)
	}
	return rcv.IsSortedBy(greater)
}

// MaxBy returns an element of AnotherTypes containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (rcv AnotherTypes) MaxBy(less func(*AnotherType, *AnotherType) bool) (result *AnotherType, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// MinBy returns an element of AnotherTypes containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (rcv AnotherTypes) MinBy(less func(*AnotherType, *AnotherType) bool) (result *AnotherType, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// Single returns exactly one element of AnotherTypes that returns true for the passed func. Returns error if no or multiple elements return true. See: http://clipperhouse.github.io/gen/#Single
func (rcv AnotherTypes) Single(fn func(*AnotherType) bool) (result *AnotherType, err error) {
	var candidate *AnotherType
	found := false
	for _, v := range rcv {
		if fn(v) {
			if found {
				err = errors.New("multiple AnotherTypes elements return true for passed func")
				return
			}
			candidate = v
			found = true
		}
	}
	if found {
		result = candidate
	} else {
		err = errors.New("no AnotherTypes elements return true for passed func")
	}
	return
}

// SortBy returns a new ordered AnotherTypes slice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv AnotherTypes) SortBy(less func(*AnotherType, *AnotherType) bool) AnotherTypes {
	result := make(AnotherTypes, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortAnotherTypes(result, less, 0, n, maxDepth)
	return result
}

// SortByDesc returns a new, descending-ordered AnotherTypes slice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv AnotherTypes) SortByDesc(less func(*AnotherType, *AnotherType) bool) AnotherTypes {
	greater := func(a, b *AnotherType) bool {
		return less(b, a)
	}
	return rcv.SortBy(greater)
}

// Where returns a new AnotherTypes slice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv AnotherTypes) Where(fn func(*AnotherType) bool) (result AnotherTypes) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapAnotherTypes(rcv AnotherTypes, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortAnotherTypes(rcv AnotherTypes, less func(*AnotherType, *AnotherType) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapAnotherTypes(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownAnotherTypes(rcv AnotherTypes, less func(*AnotherType, *AnotherType) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapAnotherTypes(rcv, first+root, first+child)
		root = child
	}
}

func heapSortAnotherTypes(rcv AnotherTypes, less func(*AnotherType, *AnotherType) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownAnotherTypes(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapAnotherTypes(rcv, first, first+i)
		siftDownAnotherTypes(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeAnotherTypes(rcv AnotherTypes, less func(*AnotherType, *AnotherType) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapAnotherTypes(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapAnotherTypes(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapAnotherTypes(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeAnotherTypes(rcv AnotherTypes, a, b, n int) {
	for i := 0; i < n; i++ {
		swapAnotherTypes(rcv, a+i, b+i)
	}
}

func doPivotAnotherTypes(rcv AnotherTypes, less func(*AnotherType, *AnotherType) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeAnotherTypes(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeAnotherTypes(rcv, less, m, m-s, m+s)
		medianOfThreeAnotherTypes(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeAnotherTypes(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapAnotherTypes(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapAnotherTypes(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapAnotherTypes(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeAnotherTypes(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeAnotherTypes(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortAnotherTypes(rcv AnotherTypes, less func(*AnotherType, *AnotherType) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortAnotherTypes(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotAnotherTypes(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortAnotherTypes(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortAnotherTypes(rcv, mhi, b)
		} else {
			quickSortAnotherTypes(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortAnotherTypes(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortAnotherTypes(rcv, less, a, b)
	}
}
