// Generated by: gen
// TypeWriter: container
// Directive: +gen on main.AnotherDifferentType

// See http://clipperhouse.github.io/gen for documentation

// List is a modification of http://golang.org/pkg/container/list/
// Ring is a modification of http://golang.org/pkg/container/ring/
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

package main

// AnotherDifferentTypeElement is an element of a linked list.
type AnotherDifferentTypeElement struct {
	// Next and previous pointers in the doubly-linked list of elements.
	// To simplify the implementation, internally a list l is implemented
	// as a ring, such that &l.root is both the next element of the last
	// list element (l.Back()) and the previous element of the first list
	// element (l.Front()).
	next, prev *AnotherDifferentTypeElement

	// The list to which this element belongs.
	list *AnotherDifferentTypeList

	// The value stored with this element.
	Value AnotherDifferentType
}

// Next returns the next list element or nil.
func (e *AnotherDifferentTypeElement) Next() *AnotherDifferentTypeElement {
	if p := e.next; e.list != nil && p != &e.list.root {
		return p
	}
	return nil
}

// Prev returns the previous list element or nil.
func (e *AnotherDifferentTypeElement) Prev() *AnotherDifferentTypeElement {
	if p := e.prev; e.list != nil && p != &e.list.root {
		return p
	}
	return nil
}

// AnotherDifferentTypeList represents a doubly linked list.
// The zero value for AnotherDifferentTypeList is an empty list ready to use.
type AnotherDifferentTypeList struct {
	root AnotherDifferentTypeElement // sentinel list element, only &root, root.prev, and root.next are used
	len  int                         // current list length excluding (this) sentinel element
}

// Init initializes or clears list l.
func (l *AnotherDifferentTypeList) Init() *AnotherDifferentTypeList {
	l.root.next = &l.root
	l.root.prev = &l.root
	l.len = 0
	return l
}

// New returns an initialized list.
func NewAnotherDifferentTypeList() *AnotherDifferentTypeList {
	return new(AnotherDifferentTypeList).Init()
}

// Len returns the number of elements of list l.
// The complexity is O(1).
func (l *AnotherDifferentTypeList) Len() int { return l.len }

// Front returns the first element of list l or nil.
func (l *AnotherDifferentTypeList) Front() *AnotherDifferentTypeElement {
	if l.len == 0 {
		return nil
	}
	return l.root.next
}

// Back returns the last element of list l or nil.
func (l *AnotherDifferentTypeList) Back() *AnotherDifferentTypeElement {
	if l.len == 0 {
		return nil
	}
	return l.root.prev
}

// lazyInit lazily initializes a zero AnotherDifferentTypeList value.
func (l *AnotherDifferentTypeList) lazyInit() {
	if l.root.next == nil {
		l.Init()
	}
}

// insert inserts e after at, increments l.len, and returns e.
func (l *AnotherDifferentTypeList) insert(e, at *AnotherDifferentTypeElement) *AnotherDifferentTypeElement {
	n := at.next
	at.next = e
	e.prev = at
	e.next = n
	n.prev = e
	e.list = l
	l.len++
	return e
}

// insertValue is a convenience wrapper for insert(&AnotherDifferentTypeElement{Value: v}, at).
func (l *AnotherDifferentTypeList) insertValue(v AnotherDifferentType, at *AnotherDifferentTypeElement) *AnotherDifferentTypeElement {
	return l.insert(&AnotherDifferentTypeElement{Value: v}, at)
}

// remove removes e from its list, decrements l.len, and returns e.
func (l *AnotherDifferentTypeList) remove(e *AnotherDifferentTypeElement) *AnotherDifferentTypeElement {
	e.prev.next = e.next
	e.next.prev = e.prev
	e.next = nil // avoid memory leaks
	e.prev = nil // avoid memory leaks
	e.list = nil
	l.len--
	return e
}

// Remove removes e from l if e is an element of list l.
// It returns the element value e.Value.
func (l *AnotherDifferentTypeList) Remove(e *AnotherDifferentTypeElement) AnotherDifferentType {
	if e.list == l {
		// if e.list == l, l must have been initialized when e was inserted
		// in l or l == nil (e is a zero AnotherDifferentTypeElement) and l.remove will crash
		l.remove(e)
	}
	return e.Value
}

// PushFront inserts a new element e with value v at the front of list l and returns e.
func (l *AnotherDifferentTypeList) PushFront(v AnotherDifferentType) *AnotherDifferentTypeElement {
	l.lazyInit()
	return l.insertValue(v, &l.root)
}

// PushBack inserts a new element e with value v at the back of list l and returns e.
func (l *AnotherDifferentTypeList) PushBack(v AnotherDifferentType) *AnotherDifferentTypeElement {
	l.lazyInit()
	return l.insertValue(v, l.root.prev)
}

// InsertBefore inserts a new element e with value v immediately before mark and returns e.
// If mark is not an element of l, the list is not modified.
func (l *AnotherDifferentTypeList) InsertBefore(v AnotherDifferentType, mark *AnotherDifferentTypeElement) *AnotherDifferentTypeElement {
	if mark.list != l {
		return nil
	}
	// see comment in AnotherDifferentTypeList.Remove about initialization of l
	return l.insertValue(v, mark.prev)
}

// InsertAfter inserts a new element e with value v immediately after mark and returns e.
// If mark is not an element of l, the list is not modified.
func (l *AnotherDifferentTypeList) InsertAfter(v AnotherDifferentType, mark *AnotherDifferentTypeElement) *AnotherDifferentTypeElement {
	if mark.list != l {
		return nil
	}
	// see comment in AnotherDifferentTypeList.Remove about initialization of l
	return l.insertValue(v, mark)
}

// MoveToFront moves element e to the front of list l.
// If e is not an element of l, the list is not modified.
func (l *AnotherDifferentTypeList) MoveToFront(e *AnotherDifferentTypeElement) {
	if e.list != l || l.root.next == e {
		return
	}
	// see comment in AnotherDifferentTypeList.Remove about initialization of l
	l.insert(l.remove(e), &l.root)
}

// MoveToBack moves element e to the back of list l.
// If e is not an element of l, the list is not modified.
func (l *AnotherDifferentTypeList) MoveToBack(e *AnotherDifferentTypeElement) {
	if e.list != l || l.root.prev == e {
		return
	}
	// see comment in AnotherDifferentTypeList.Remove about initialization of l
	l.insert(l.remove(e), l.root.prev)
}

// MoveBefore moves element e to its new position before mark.
// If e or mark is not an element of l, or e == mark, the list is not modified.
func (l *AnotherDifferentTypeList) MoveBefore(e, mark *AnotherDifferentTypeElement) {
	if e.list != l || e == mark || mark.list != l {
		return
	}
	l.insert(l.remove(e), mark.prev)
}

// MoveAfter moves element e to its new position after mark.
// If e is not an element of l, or e == mark, the list is not modified.
func (l *AnotherDifferentTypeList) MoveAfter(e, mark *AnotherDifferentTypeElement) {
	if e.list != l || e == mark || mark.list != l {
		return
	}
	l.insert(l.remove(e), mark)
}

// PushBackList inserts a copy of an other list at the back of list l.
// The lists l and other may be the same.
func (l *AnotherDifferentTypeList) PushBackList(other *AnotherDifferentTypeList) {
	l.lazyInit()
	for i, e := other.Len(), other.Front(); i > 0; i, e = i-1, e.Next() {
		l.insertValue(e.Value, l.root.prev)
	}
}

// PushFrontList inserts a copy of an other list at the front of list l.
// The lists l and other may be the same.
func (l *AnotherDifferentTypeList) PushFrontList(other *AnotherDifferentTypeList) {
	l.lazyInit()
	for i, e := other.Len(), other.Back(); i > 0; i, e = i-1, e.Prev() {
		l.insertValue(e.Value, &l.root)
	}
}

// The primary type that represents a set
type AnotherDifferentTypeSet map[AnotherDifferentType]struct{}

// Creates and returns a reference to an empty set.
func NewAnotherDifferentTypeSet() AnotherDifferentTypeSet {
	return make(AnotherDifferentTypeSet)
}

// Creates and returns a reference to a set from an existing slice
func NewAnotherDifferentTypeSetFromSlice(s []AnotherDifferentType) AnotherDifferentTypeSet {
	a := NewAnotherDifferentTypeSet()
	for _, item := range s {
		a.Add(item)
	}
	return a
}

// Adds an item to the current set if it doesn't already exist in the set.
func (set AnotherDifferentTypeSet) Add(i AnotherDifferentType) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Determines if a given item is already in the set.
func (set AnotherDifferentTypeSet) Contains(i AnotherDifferentType) bool {
	_, found := set[i]
	return found
}

// Determines if the given items are all in the set
func (set AnotherDifferentTypeSet) ContainsAll(i ...AnotherDifferentType) bool {
	allSet := NewAnotherDifferentTypeSetFromSlice(i)
	if allSet.IsSubset(set) {
		return true
	}
	return false
}

// Determines if every item in the other set is in this set.
func (set AnotherDifferentTypeSet) IsSubset(other AnotherDifferentTypeSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Determines if every item of this set is in the other set.
func (set AnotherDifferentTypeSet) IsSuperset(other AnotherDifferentTypeSet) bool {
	return other.IsSubset(set)
}

// Returns a new set with all items in both sets.
func (set AnotherDifferentTypeSet) Union(other AnotherDifferentTypeSet) AnotherDifferentTypeSet {
	unionedSet := NewAnotherDifferentTypeSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Returns a new set with items that exist only in both sets.
func (set AnotherDifferentTypeSet) Intersect(other AnotherDifferentTypeSet) AnotherDifferentTypeSet {
	intersection := NewAnotherDifferentTypeSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Returns a new set with items in the current set but not in the other set
func (set AnotherDifferentTypeSet) Difference(other AnotherDifferentTypeSet) AnotherDifferentTypeSet {
	differencedSet := NewAnotherDifferentTypeSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// Returns a new set with items in the current set or the other set but not in both.
func (set AnotherDifferentTypeSet) SymmetricDifference(other AnotherDifferentTypeSet) AnotherDifferentTypeSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clears the entire set to be the empty set.
func (set *AnotherDifferentTypeSet) Clear() {
	*set = make(AnotherDifferentTypeSet)
}

// Allows the removal of a single item in the set.
func (set AnotherDifferentTypeSet) Remove(i AnotherDifferentType) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set AnotherDifferentTypeSet) Cardinality() int {
	return len(set)
}

// Iter() returns a channel of type AnotherDifferentType that you can range over.
func (set AnotherDifferentTypeSet) Iter() <-chan AnotherDifferentType {
	ch := make(chan AnotherDifferentType)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set AnotherDifferentTypeSet) Equal(other AnotherDifferentTypeSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Returns a clone of the set.
// Does NOT clone the underlying elements.
func (set AnotherDifferentTypeSet) Clone() AnotherDifferentTypeSet {
	clonedSet := NewAnotherDifferentTypeSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}

// A Ring is an element of a circular list, or ring.
// Rings do not have a beginning or end; a pointer to any ring element
// serves as reference to the entire ring. Empty rings are represented
// as nil Ring pointers. The zero value for a Ring is a one-element
// ring with a nil Value.
//
type AnotherDifferentTypeRing struct {
	next, prev *AnotherDifferentTypeRing
	Value      AnotherDifferentType // for use by client; untouched by this library
}

func (r *AnotherDifferentTypeRing) init() *AnotherDifferentTypeRing {
	r.next = r
	r.prev = r
	return r
}

// Next returns the next ring element. r must not be empty.
func (r *AnotherDifferentTypeRing) Next() *AnotherDifferentTypeRing {
	if r.next == nil {
		return r.init()
	}
	return r.next
}

// Prev returns the previous ring element. r must not be empty.
func (r *AnotherDifferentTypeRing) Prev() *AnotherDifferentTypeRing {
	if r.next == nil {
		return r.init()
	}
	return r.prev
}

// Move moves n % r.Len() elements backward (n < 0) or forward (n >= 0)
// in the ring and returns that ring element. r must not be empty.
//
func (r *AnotherDifferentTypeRing) Move(n int) *AnotherDifferentTypeRing {
	if r.next == nil {
		return r.init()
	}
	switch {
	case n < 0:
		for ; n < 0; n++ {
			r = r.prev
		}
	case n > 0:
		for ; n > 0; n-- {
			r = r.next
		}
	}
	return r
}

// New creates a ring of n elements.
func NewAnotherDifferentTypeRing(n int) *AnotherDifferentTypeRing {
	if n <= 0 {
		return nil
	}
	r := new(AnotherDifferentTypeRing)
	p := r
	for i := 1; i < n; i++ {
		p.next = &AnotherDifferentTypeRing{prev: p}
		p = p.next
	}
	p.next = r
	r.prev = p
	return r
}

// Link connects ring r with ring s such that r.Next()
// becomes s and returns the original value for r.Next().
// r must not be empty.
//
// If r and s point to the same ring, linking
// them removes the elements between r and s from the ring.
// The removed elements form a subring and the result is a
// reference to that subring (if no elements were removed,
// the result is still the original value for r.Next(),
// and not nil).
//
// If r and s point to different rings, linking
// them creates a single ring with the elements of s inserted
// after r. The result points to the element following the
// last element of s after insertion.
//
func (r *AnotherDifferentTypeRing) Link(s *AnotherDifferentTypeRing) *AnotherDifferentTypeRing {
	n := r.Next()
	if s != nil {
		p := s.Prev()
		// Note: Cannot use multiple assignment because
		// evaluation order of LHS is not specified.
		r.next = s
		s.prev = r
		n.prev = p
		p.next = n
	}
	return n
}

// Unlink removes n % r.Len() elements from the ring r, starting
// at r.Next(). If n % r.Len() == 0, r remains unchanged.
// The result is the removed subring. r must not be empty.
//
func (r *AnotherDifferentTypeRing) Unlink(n int) *AnotherDifferentTypeRing {
	if n <= 0 {
		return nil
	}
	return r.Link(r.Move(n + 1))
}

// Len computes the number of elements in ring r.
// It executes in time proportional to the number of elements.
//
func (r *AnotherDifferentTypeRing) Len() int {
	n := 0
	if r != nil {
		n = 1
		for p := r.Next(); p != r; p = p.next {
			n++
		}
	}
	return n
}

// Do calls function f on each element of the ring, in forward order.
// The behavior of Do is undefined if f changes *r.
func (r *AnotherDifferentTypeRing) Do(f func(AnotherDifferentType)) {
	if r != nil {
		f(r.Value)
		for p := r.Next(); p != r; p = p.next {
			f(p.Value)
		}
	}
}
