// Generated by: gen
// TypeWriter: gen
// Directive: +gen on main.DifferentType

// See http://clipperhouse.github.io/gen for documentation

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

package main

import (
	"errors"
)

// DifferentTypes is a slice of type DifferentType. Use it where you would use []DifferentType.
type DifferentTypes []DifferentType

// All verifies that all elements of DifferentTypes return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv DifferentTypes) All(fn func(DifferentType) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of DifferentTypes return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv DifferentTypes) Any(fn func(DifferentType) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// Count gives the number elements of DifferentTypes that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv DifferentTypes) Count(fn func(DifferentType) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}

// Distinct returns a new DifferentTypes slice whose elements are unique. See: http://clipperhouse.github.io/gen/#Distinct
func (rcv DifferentTypes) Distinct() (result DifferentTypes) {
	appended := make(map[DifferentType]bool)
	for _, v := range rcv {
		if !appended[v] {
			result = append(result, v)
			appended[v] = true
		}
	}
	return result
}

// DistinctBy returns a new DifferentTypes slice whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv DifferentTypes) DistinctBy(equal func(DifferentType, DifferentType) bool) (result DifferentTypes) {
	for _, v := range rcv {
		eq := func(_app DifferentType) bool {
			return equal(v, _app)
		}
		if !result.Any(eq) {
			result = append(result, v)
		}
	}
	return result
}

// Each iterates over DifferentTypes and executes the passed func against each element. See: http://clipperhouse.github.io/gen/#Each
func (rcv DifferentTypes) Each(fn func(DifferentType)) {
	for _, v := range rcv {
		fn(v)
	}
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv DifferentTypes) First(fn func(DifferentType) bool) (result DifferentType, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no DifferentTypes elements return true for passed func")
	return
}

// IsSortedBy reports whether an instance of DifferentTypes is sorted, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv DifferentTypes) IsSortedBy(less func(DifferentType, DifferentType) bool) bool {
	n := len(rcv)
	for i := n - 1; i > 0; i-- {
		if less(rcv[i], rcv[i-1]) {
			return false
		}
	}
	return true
}

// IsSortedDesc reports whether an instance of DifferentTypes is sorted in descending order, using the pass func to define ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv DifferentTypes) IsSortedByDesc(less func(DifferentType, DifferentType) bool) bool {
	greater := func(a, b DifferentType) bool {
		return less(b, a)
	}
	return rcv.IsSortedBy(greater)
}

// MaxBy returns an element of DifferentTypes containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (rcv DifferentTypes) MaxBy(less func(DifferentType, DifferentType) bool) (result DifferentType, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// MinBy returns an element of DifferentTypes containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (rcv DifferentTypes) MinBy(less func(DifferentType, DifferentType) bool) (result DifferentType, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// Single returns exactly one element of DifferentTypes that returns true for the passed func. Returns error if no or multiple elements return true. See: http://clipperhouse.github.io/gen/#Single
func (rcv DifferentTypes) Single(fn func(DifferentType) bool) (result DifferentType, err error) {
	var candidate DifferentType
	found := false
	for _, v := range rcv {
		if fn(v) {
			if found {
				err = errors.New("multiple DifferentTypes elements return true for passed func")
				return
			}
			candidate = v
			found = true
		}
	}
	if found {
		result = candidate
	} else {
		err = errors.New("no DifferentTypes elements return true for passed func")
	}
	return
}

// SortBy returns a new ordered DifferentTypes slice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv DifferentTypes) SortBy(less func(DifferentType, DifferentType) bool) DifferentTypes {
	result := make(DifferentTypes, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortDifferentTypes(result, less, 0, n, maxDepth)
	return result
}

// SortByDesc returns a new, descending-ordered DifferentTypes slice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv DifferentTypes) SortByDesc(less func(DifferentType, DifferentType) bool) DifferentTypes {
	greater := func(a, b DifferentType) bool {
		return less(b, a)
	}
	return rcv.SortBy(greater)
}

// Where returns a new DifferentTypes slice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv DifferentTypes) Where(fn func(DifferentType) bool) (result DifferentTypes) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// AggregateInt iterates over DifferentTypes, operating on each element while maintaining ‘state’. See: http://clipperhouse.github.io/gen/#Aggregate
func (rcv DifferentTypes) AggregateInt(fn func(int, DifferentType) int) (result int) {
	for _, v := range rcv {
		result = fn(result, v)
	}
	return
}

// AverageInt sums int over all elements and divides by len(DifferentTypes). See: http://clipperhouse.github.io/gen/#Average
// AVERAGE START OMIT
func (rcv DifferentTypes) AverageInt(fn func(DifferentType) int) (result int, err error) {
	// AVERAGE END OMIT
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine AverageInt of zero-length DifferentTypes")
		return
	}
	for _, v := range rcv {
		result += fn(v)
	}
	result = result / int(l)
	return
}

// GroupByInt groups elements into a map keyed by int. See: http://clipperhouse.github.io/gen/#GroupBy
// GROUPBY START OMIT
func (rcv DifferentTypes) GroupByInt(fn func(DifferentType) int) map[int]DifferentTypes {
	// GROUPBY END OMIT
	result := make(map[int]DifferentTypes)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// MaxInt selects the largest value of int in DifferentTypes. Returns error on DifferentTypes with no elements. See: http://clipperhouse.github.io/gen/#MaxCustom
func (rcv DifferentTypes) MaxInt(fn func(DifferentType) int) (result int, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine MaxInt of zero-length DifferentTypes")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f > result {
				result = f
			}
		}
	}
	return
}

// MinInt selects the least value of int in DifferentTypes. Returns error on DifferentTypes with no elements. See: http://clipperhouse.github.io/gen/#MinCustom
func (rcv DifferentTypes) MinInt(fn func(DifferentType) int) (result int, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine MinInt of zero-length DifferentTypes")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f < result {
				result = f
			}
		}
	}
	return
}

// SelectInt returns a slice of int in DifferentTypes, projected by passed func. See: http://clipperhouse.github.io/gen/#Select
func (rcv DifferentTypes) SelectInt(fn func(DifferentType) int) (result []int) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}

// SumInt sums int over elements in DifferentTypes. See: http://clipperhouse.github.io/gen/#Sum
func (rcv DifferentTypes) SumInt(fn func(DifferentType) int) (result int) {
	for _, v := range rcv {
		result += fn(v)
	}
	return
}

// AggregateString iterates over DifferentTypes, operating on each element while maintaining ‘state’. See: http://clipperhouse.github.io/gen/#Aggregate
func (rcv DifferentTypes) AggregateString(fn func(string, DifferentType) string) (result string) {
	for _, v := range rcv {
		result = fn(result, v)
	}
	return
}

// GroupByString groups elements into a map keyed by string. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv DifferentTypes) GroupByString(fn func(DifferentType) string) map[string]DifferentTypes {
	result := make(map[string]DifferentTypes)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// MaxString selects the largest value of string in DifferentTypes. Returns error on DifferentTypes with no elements. See: http://clipperhouse.github.io/gen/#MaxCustom
func (rcv DifferentTypes) MaxString(fn func(DifferentType) string) (result string, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine MaxString of zero-length DifferentTypes")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f > result {
				result = f
			}
		}
	}
	return
}

// MinString selects the least value of string in DifferentTypes. Returns error on DifferentTypes with no elements. See: http://clipperhouse.github.io/gen/#MinCustom
func (rcv DifferentTypes) MinString(fn func(DifferentType) string) (result string, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine MinString of zero-length DifferentTypes")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f < result {
				result = f
			}
		}
	}
	return
}

// SelectString returns a slice of string in DifferentTypes, projected by passed func. See: http://clipperhouse.github.io/gen/#Select
func (rcv DifferentTypes) SelectString(fn func(DifferentType) string) (result []string) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapDifferentTypes(rcv DifferentTypes, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortDifferentTypes(rcv DifferentTypes, less func(DifferentType, DifferentType) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapDifferentTypes(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownDifferentTypes(rcv DifferentTypes, less func(DifferentType, DifferentType) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapDifferentTypes(rcv, first+root, first+child)
		root = child
	}
}

func heapSortDifferentTypes(rcv DifferentTypes, less func(DifferentType, DifferentType) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownDifferentTypes(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapDifferentTypes(rcv, first, first+i)
		siftDownDifferentTypes(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeDifferentTypes(rcv DifferentTypes, less func(DifferentType, DifferentType) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapDifferentTypes(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapDifferentTypes(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapDifferentTypes(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeDifferentTypes(rcv DifferentTypes, a, b, n int) {
	for i := 0; i < n; i++ {
		swapDifferentTypes(rcv, a+i, b+i)
	}
}

func doPivotDifferentTypes(rcv DifferentTypes, less func(DifferentType, DifferentType) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeDifferentTypes(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeDifferentTypes(rcv, less, m, m-s, m+s)
		medianOfThreeDifferentTypes(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeDifferentTypes(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapDifferentTypes(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapDifferentTypes(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapDifferentTypes(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeDifferentTypes(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeDifferentTypes(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortDifferentTypes(rcv DifferentTypes, less func(DifferentType, DifferentType) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortDifferentTypes(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotDifferentTypes(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortDifferentTypes(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortDifferentTypes(rcv, mhi, b)
		} else {
			quickSortDifferentTypes(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortDifferentTypes(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortDifferentTypes(rcv, less, a, b)
	}
}
